// Copyright 2021 Adam Chalkley
//
// https://github.com/atc0005/check-whois
//
// Licensed under the MIT License. See LICENSE file in the project root for
// full license information.

//go:generate go-winres make --product-version=git-tag --file-version=git-tag

package main

import (
	"errors"
	"fmt"
	"time"

	"github.com/openrdap/rdap"
	"github.com/openrdap/rdap/bootstrap"
	"github.com/openrdap/rdap/bootstrap/cache"
	zlog "github.com/rs/zerolog/log"

	"github.com/atc0005/check-whois/internal/config"
	"github.com/atc0005/check-whois/internal/domain/metadata"

	"github.com/atc0005/go-nagios"
)

func main() {

	plugin := nagios.NewPlugin()

	// defer this from the start so it is the last deferred function to run
	defer plugin.ReturnCheckResults()

	// Setup configuration by parsing user-provided flags.
	cfg, cfgErr := config.New()
	switch {
	case errors.Is(cfgErr, config.ErrVersionRequested):
		fmt.Println(config.Version())

		return

	case cfgErr != nil:
		// We're using the standalone Err function from rs/zerolog/log as we
		// do not have a working configuration.
		zlog.Err(cfgErr).Msg("Error initializing application")
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error initializing application",
			nagios.StateUNKNOWNLabel,
		)
		plugin.AddError(cfgErr)
		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode

		return
	}

	// Use provided threshold values to calculate the expiration times that
	// should trigger either a WARNING or CRITICAL state.
	now := time.Now().UTC()
	domainExpireAgeWarning := now.AddDate(0, 0, cfg.AgeWarning)
	domainExpireAgeCritical := now.AddDate(0, 0, cfg.AgeCritical)

	plugin.WarningThreshold = fmt.Sprintf(
		"Expires before %v (%d days)",
		domainExpireAgeWarning.Format(metadata.DomainDateLayout),
		cfg.AgeWarning,
	)
	plugin.CriticalThreshold = fmt.Sprintf(
		"Expires before %v (%d days)",
		domainExpireAgeCritical.Format(metadata.DomainDateLayout),
		cfg.AgeCritical,
	)

	if cfg.EmitBranding {
		// If enabled, show application details at end of notification
		plugin.BrandingCallback = config.Branding("Notification generated by ")
	}

	log := cfg.Log.With().
		Str("domain", cfg.Domain).
		Logger()

	var err error

	var d *metadata.Domain

	// We track the datasource locally for scenarios where we fail to resolve
	// metadata for a given domain.
	var dataSource string

	// Create new cache using embedded local file.
	bootstrapCache := cache.NewMemoryCache()
	if err := bootstrapCache.Save(bootstrap.DNS.Filename(), bootstrapRegistryFile); err != nil {
		// We should not be encountering an error at this point unless the
		// embedded JSON file is malformed. If that's the case, we need to
		// immediately abort.
		log.Error().Err(err).Msgf("Error initializing application")
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error initializing application: %s",
			nagios.StateUNKNOWNLabel,
			err,
		)
		plugin.AddError(err)
		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode

		return
	}

	// The RDAP client is used for determining whether RDAP query support is
	// available for a given domain as well as making the actual query if it
	// is.
	rdapClient := &rdap.Client{
		Bootstrap: &bootstrap.Client{
			Cache: bootstrapCache,
		},

		Verbose: RDAPDebugLogger(&log),
	}

	switch {
	case mustUseWHOIS(cfg.Domain, rdapClient):
		log.Debug().Msg("RDAP query support for domain unavailable, performing WHOIS query instead.")

		d, err = whoisQuery(cfg, domainExpireAgeWarning, domainExpireAgeCritical)
		dataSource = metadata.DataSourceWHOIS

	default:
		log.Debug().Msg("RDAP query support for domain available, performing RDAP query.")

		d, err = rdapQuery(cfg, rdapClient, domainExpireAgeWarning, domainExpireAgeCritical)
		dataSource = metadata.DataSourceRDAP
	}

	log = log.With().
		Str("query_type", dataSource).
		Logger()

	if err != nil {
		log.Error().Err(err).Msgf("failed to query %s data", dataSource)

		plugin.AddError(err)
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Error retrieving %s data for %s domain",
			nagios.StateUNKNOWNLabel,
			dataSource,
			cfg.Domain,
		)
		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode

		return
	}

	pd, perfDataErr := getPerfData(d, cfg.AgeCritical, cfg.AgeWarning)
	if perfDataErr != nil {
		log.Error().
			Err(perfDataErr).
			Msg("failed to generate performance data")

		// Surface the error in plugin output.
		plugin.AddError(perfDataErr)

		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Failed to generate performance data metrics",
			nagios.StateUNKNOWNLabel,
		)

		return
	}

	if err := plugin.AddPerfData(false, pd...); err != nil {
		log.Error().
			Err(err).
			Msg("failed to add performance data")

		// Surface the error in plugin output.
		plugin.AddError(err)

		plugin.ExitStatusCode = nagios.StateUNKNOWNExitCode
		plugin.ServiceOutput = fmt.Sprintf(
			"%s: Failed to process performance data metrics",
			nagios.StateUNKNOWNLabel,
		)

		return
	}

	switch {

	case d.IsExpired():

		log.Error().Msg("Domain has expired")

		plugin.AddError(metadata.ErrDomainExpired)
		plugin.ServiceOutput = d.OneLineCheckSummary()
		plugin.LongServiceOutput = d.Report()
		plugin.ExitStatusCode = d.ServiceState().ExitCode

		return

	case d.IsExpiring():

		log.Warn().Msg("Domain is expiring")

		plugin.AddError(metadata.ErrDomainExpiring)
		plugin.ServiceOutput = d.OneLineCheckSummary()
		plugin.LongServiceOutput = d.Report()
		plugin.ExitStatusCode = d.ServiceState().ExitCode

		return

	default:

		log.Debug().Msg("No problems with expiration date for domain detected")

		plugin.ServiceOutput = d.OneLineCheckSummary()
		plugin.LongServiceOutput = d.Report()
		plugin.ExitStatusCode = nagios.StateOKExitCode

		return

	}

}
